# Generated by Django 5.2.8 on 2025-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cutoff_score', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
