# Generated by Django 5.2.8 on 2025-12-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uni_logos/'),
        ),
    ]
